# Generated by Django 4.1.2 on 2022-11-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('beermanagment', '0001_initial'), ('beermanagment', '0002_bar'), ('beermanagment', '0003_order_stock_orderitem'), ('beermanagment', '0004_alter_reference_options_alter_orderitem_order'), ('beermanagment', '0005_alter_bar_options_alter_order_options_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beermanagment.bar')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beermanagment.order')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beermanagment.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beermanagment.bar')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beermanagment.reference')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
