# Generated by Django 4.1.2 on 2022-10-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beermanagment', '0003_order_stock_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beermanagment.order'),
        ),
    ]
